package logger

import "fmt"

// msg returns the localized string for key in lang, falling back to Japanese.
//
// The *T() logger methods call this twice (ja and en) and store both
// renderings in one JSON Lines entry, so the dashboard can switch language
// without re-reading the log. An unknown key returns the key itself, so a
// missing translation is visible in the log instead of silently empty.
func msg(lang, key string, args ...interface{}) string {
	table, ok := catalog[lang]
	if !ok {
		table = catalog["ja"]
	}
	s, ok := table[key]
	if !ok || s == "" {
		s = catalog["ja"][key]
	}
	if s == "" {
		s = key
	}
	if len(args) == 0 {
		return s
	}
	return fmt.Sprintf(s, args...)
}

// catalog holds the ja/en renderings used by the logger *T() methods. Keys are
// grouped by component (agent / dash). Add new entries in both languages.
var catalog = map[string]map[string]string{
	"ja": {
		// --- agent ---
		"agent.start":              "エージェント起動 (送信間隔: %.1f秒, 接続先: %s)",
		"agent.shutdown_signal":    "シャットダウンシグナル受信",
		"agent.exit":               "エージェント終了",
		"agent.sys_modules":        "システムモジュール登録: 収集間隔=%d秒",
		"agent.plugins_dir":        "プラグインディレクトリ: %s",
		"agent.sig_verify_enabled": "プラグイン署名検証: 有効（公開鍵: %s）— 未署名・署名不一致の .so は読み込みません",
		"agent.modules_missing":    "modules.json が見つかりません（スキップ）: %s",
		"agent.plugin_disabled":    "プラグイン '%s' を無効化し停止しました",
		"agent.plugin_skip":        "プラグイン '%s' は無効のためスキップ",
		"agent.plugin_config":      "プラグイン '%s' の設定を更新しました",
		"agent.plugin_registered":  "プラグイン '%s' を登録しました",
		"agent.plugin_removed":     "プラグイン '%s' を modules.json から削除されたため停止しました",
		"agent.plugin_sig_ok":      "プラグイン署名を検証しました: %s",
		"agent.modules_changed":    "modules.json の変更を検知、再読み込みします",
		"agent.ws_connected":       "WebSocket 接続確立",
		"agent.sec_event_sent":     "セキュリティイベント送信: [%s] %s (%s)",
		"agent.sec_event_failed":   "セキュリティイベント送信失敗: %v",
		"agent.sec_event_panic":    "セキュリティイベント取得でパニック: %v",
		"agent.manual_recv":        "手動実行リクエスト受信: plugin=%s request_id=%s",
		"agent.manual_sent":        "手動実行結果送信: plugin=%s status=%s duration=%dms",
		"agent.dep_missing":        "必要なコマンドが見つかりません: %s（%s で使用）",
		"agent.dep_missing_list":   "不足ツール: %v — %s",

		// --- dashboard ---
		"dash.security_alert":      "セキュリティアラート: [%s] %s",
		"dash.start":               "ダッシュボード起動 (listen: %s)",
		"dash.static_dir":          "静的ファイルディレクトリ: %s",
		"dash.shutdown_signal":     "シャットダウンシグナル受信",
		"dash.notify_on":           "通知機能: 有効",
		"dash.notify_off":          "通知機能: 無効（チャンネル未設定）",
		"dash.alert_history":       "アラート履歴の永続化: %s",
		"dash.modules_loaded":      "モジュール設定読み込み: %s (%d モジュール)",
		"dash.agent_token_on":      "Agent トークン認証: 有効",
		"dash.client_connected":    "クライアント接続: %s",
		"dash.agent_authenticated": "Agent 認証済み接続: %s",
		"dash.agent_identified":    "Agent 識別: %s",
		"dash.api_plugins":         "プラグイン API 有効",
		"dash.api_metrics":         "メトリクス API 有効",
		"dash.api_logs":            "ログ API 有効",
		"dash.api_config":          "設定 API 有効",
		"dash.api_alert_history":   "アラート履歴 API 有効",
		"dash.api_actions":         "ワンクリック対処 API 有効",
		"dash.api_version":         "バージョン API 有効",
		"dash.api_metrics_hist":    "メトリクス履歴 API 有効",
		"dash.api_alert_settings":  "アラート設定 API 有効",
		"dash.session_persist":     "セッション永続化: %s (IPバインド: %v)",
		"dash.session_no_persist":  "セッション永続化: 無効（再起動でログアウト）",
		"dash.public_viewer":       "公開ビューアモード: 有効（ログイン不要で CPU/メモリ/ディスク使用率を閲覧可能）",
		"dash.auth_on":             "認証: 有効（ユーザー数: %d, users_file: %s）",
		"dash.auth_off":            "認証: 無効（dashboard_config.json の auth.enabled を true にすると有効化）",
		"dash.shutdown_stopping":   "シャットダウンシグナル受信、サーバー停止中...",
		"dash.server_start":        "サーバー開始: http://%s",
		"dash.server_stop":         "サーバー停止",

		// --- batch 1: agent WARN/ERROR/startup INFO ---
		"agent.autoupdate_on":          "自動更新が有効です。GitHub リポジトリが侵害されると任意コード実行につながります（%s）",
		"agent.sys_module_cfg_failed":  "システムモジュール設定失敗: %v",
		"agent.sys_module_reg_failed":  "システムモジュール登録失敗: %v",
		"agent.sig_verify_disabled":    "プラグイン署名検証: 無効 — 未署名の .so も読み込まれます（plugins.require_signature=true で有効化できます）",
		"agent.plugin_load_error":      "プラグイン読み込みエラー: %v",
		"agent.run_error":              "エージェント実行エラー: %v, 5秒後に再接続",
		"agent.plugin_stop_failed":     "プラグイン '%s' の停止に失敗: %v",
		"agent.plugin_reconfig_failed": "プラグイン '%s' の再設定失敗: %v",
		"agent.plugin_path_invalid":    "プラグイン '%s' の plugin_path が不正です",
		"agent.plugin_rejected":        "プラグイン '%s' を拒否しました: %v",
		"agent.plugin_load_failed":     "プラグイン '%s' の読み込み失敗: %v",
		"agent.plugin_name_mismatch":   "プラグイン '%s' は自身を '%s' として登録しました（modules.json の name と不一致）。events/backup の欠落を防ぐため '%s' として追跡します",
		"agent.plugin_ctor_panic":      "プラグインのコンストラクタがパニックしました: %v",
		"agent.plugin_reload_failed":   "プラグイン再読み込み失敗: %v",
		"agent.ping_failed":            "Ping 送信失敗: %v",
		"agent.read_error":             "読み取りエラー: %v",
		"agent.send_failed":            "送信失敗: %v",
		"agent.status_sent":            "ステータス送信成功",
		"agent.cmd_parse_failed":       "コマンドのパース失敗: %v",
		"agent.cmd_unknown":            "未対応のアクション: %s",
		"agent.backup_panic":           "バックアップ実行でパニック: %v",
		"agent.backup_json_failed":     "backup_result のJSON化失敗: %v",
		"agent.backup_send_failed":     "backup_result の送信失敗: %v",

		// --- batch 1: dashboard WARN/ERROR/startup INFO ---
		"dash.modules_load_error":       "モジュール設定読み込みエラー: %v",
		"dash.flood_detected":           "接続フラッド検知: %d 件拒否 (%s)",
		"dash.auth_reject_detected":     "不正Agent接続検知: %s x%d",
		"dash.agent_token_mismatch":     "Agent トークン不一致の接続を拒否: %s",
		"dash.ws_upgrade_failed":        "WebSocket アップグレード失敗: %v",
		"dash.agent_dup_rejected":       "既にAgent接続があるため、2つ目のAgent接続を拒否: %s",
		"dash.read_error":               "読み取りエラー: %v",
		"dash.event_ignored":            "非Agentからのイベントを無視: %s",
		"dash.event_received":           "イベント受信: %s",
		"dash.cmd_ignored":              "コマンド受信（無視）: %s",
		"dash.status_ignored":           "非Agentからのステータスを無視: %s",
		"dash.heuristic_rejected":       "既にAgent接続があるため、ヒューリスティック昇格を拒否: %s",
		"dash.pluginmgr_init_failed":    "PluginManager 初期化失敗: %v",
		"dash.plugin_api_disabled":      "プラグイン API は無効化されます",
		"dash.users_load_failed":        "ユーザーストア読み込み失敗: %v",
		"dash.session_load_failed":      "セッション永続化の読み込みに失敗（メモリのみで続行）: %v",
		"dash.users_corrupt":            "認証は有効ですが users.json が破損しています。管理者が手動で修正するまでログインできません: %s",
		"dash.no_users":                 "認証は有効ですがユーザーが未作成です。ブラウザで /setup.html にアクセスして管理者を作成してください",
		"dash.agent_token_missing":      "認証は有効ですが auth.agent_token が未設定です。Agent は接続できません（agent_config.json の token と同じ値を設定してください）。",
		"dash.insecure_upload":          "セキュリティ警告: plugins_upload_enabled=true かつ auth.enabled=false です。誰でもプラグイン(.so)を設置・実行できる状態（実質RCE）です。auth.enabled=true にするか plugins_upload_enabled=false にしてください。",
		"dash.shutdown_error":           "サーバーシャットダウンエラー: %v",
		"dash.server_start_failed":      "サーバー起動失敗: %v",
		"dash.alert_history_signed":     "アラート履歴のHMAC署名: 有効 (鍵: %s)",
		"dash.alert_history_key_failed": "アラート履歴の署名鍵を読み込めません（無署名で続行）: %v",

		// --- batch 2: dashboard Hub / updater / alert / notify ---
		"dash.broadcast_error":          "Broadcast 送信エラー: %v, クライアントを削除します",
		"dash.viewer_cap":               "未認証ビューアの上限 (%d) に達したため、接続を拒否しました",
		"dash.evict_viewer":             "認証済みクライアントのため、未認証ビューアを1件切断しました (上限 %d)",
		"dash.max_clients":              "最大接続数 (%d) に達したため、接続を拒否しました",
		"dash.client_added":             "クライアント追加: %s (現在 %d 接続)",
		"dash.client_removed":           "クライアント削除: %s (残り %d 接続)",
		"dash.client_close_error":       "クライアント Close エラー: %v",
		"dash.invalid_status":           "不正なステータスを破棄しました: %v",
		"dash.broadcast_browsers_error": "BroadcastToBrowsers 送信エラー: %v",
		"updater.incomplete":            "自動更新: 設定が不完全です（repository_url / update_script）",
		"updater.enabled":               "自動更新: 有効（確認間隔: %s, 現在: %s）",
		"updater.check_failed":          "自動更新: バージョン確認失敗: %v",
		"updater.latest":                "自動更新: 最新版です (%s)",
		"updater.new_version":           "自動更新: 新バージョン検知 %s → %s。更新スクリプトを実行します",
		"updater.script_failed":         "自動更新: スクリプト実行失敗: %v",
		"updater.script_done":           "自動更新: 更新スクリプト完了（次回起動で反映されます）",
		"updater.output":                "自動更新: %s 出力:\n%s",
		"alert.history_load_failed":     "アラート履歴の読み込み失敗: %v",
		"notify.disabled":               "通知機能は無効です",
		"notify.discord_reg":            "通知チャンネル登録: discord (リトライ=%d, バックオフ上限=%ds)",
		"notify.telegram_reg":           "通知チャンネル登録: telegram",
		"notify.line_reg":               "通知チャンネル登録: line",
		"notify.slack_reg":              "通知チャンネル登録: slack",
		"notify.email_reg":              "通知チャンネル登録: email",
		"notify.channel_count":          "通知チャンネル数: %d",
		"notify.batch_enabled":          "通知バッチ集約: 有効 (窓=%s, critical除外=%v)",
		"notify.send":                   "通知送信: [%s] %s",
		"notify.concurrent_skip":        "通知の同時実行が上限(%d)のため [%s] への送信をスキップしました",
		"notify.timeout_skip":           "重大通知の送信待ちがタイムアウトしたため [%s] への送信をスキップしました",
		"notify.panic":                  "通知送信でパニック [%s]: %v",
		"notify.failed":                 "通知失敗 [%s]: %v",
		"notify.success":                "通知成功 [%s]",

		// --- batch 3a: internal/api / internal/auth ---
		"api.bwrap_missing":           "プラグイン検査の隔離に必要な bwrap が見つかりません (%s)。アップロードは拒否されます（plugins.inspect_isolation=\"off\" で従来動作）: %v",
		"api.plugin_run_request":      "手動実行リクエスト送信: plugin=%s request_id=%s",
		"api.plugin_upload_recv":      "プラグインアップロード受信: %s (%d bytes) from %s",
		"api.plugin_sig_failed":       "プラグイン署名検証に失敗したため拒否: %s: %v",
		"api.plugin_sig_ok":           "プラグイン署名を検証しました（検査前）: %s",
		"api.plugin_verify_failed":    "プラグイン検証失敗のため拒否: %s: %v",
		"api.module_register_failed":  "モジュール登録失敗: %s: %v",
		"api.plugin_so_delete_failed": "プラグイン .so の削除に失敗: %s: %v",
		"api.plugin_module_deleted":   "プラグインモジュール削除: %s",
		"api.alertcfg_updated":        "アラート閾値を更新し、dashboard_config.json に保存しました",
		"auth.setup_done":             "初回セットアップ完了: 管理者 '%s' を作成しました",
		"auth.login_locked":           "ログイン試行がロック中: ip=%s",
		"auth.login_failed":           "ログイン失敗: user=%s from=%s",
		"auth.login_success":          "ログイン成功: user=%s role=%s from=%s",
		"auth.guest_login":            "ゲストログイン: role=viewer from=%s",
		"auth.password_changed":       "パスワード変更: user=%s",
		"auth.user_created":           "ユーザー作成: %s (role=%s)",
		"auth.user_deleted":           "ユーザー削除: %s",
		"auth.avatar_updated":         "アバター更新: user=%s",
	},
	"en": {
		// --- agent ---
		"agent.start":              "Agent started (interval: %.1fs, dashboard: %s)",
		"agent.shutdown_signal":    "Shutdown signal received",
		"agent.exit":               "Agent stopped",
		"agent.sys_modules":        "System modules registered: collection interval=%ds",
		"agent.plugins_dir":        "Plugins directory: %s",
		"agent.sig_verify_enabled": "Plugin signature verification: enabled (public key: %s) — unsigned or mismatched .so files are not loaded",
		"agent.modules_missing":    "modules.json not found (skipped): %s",
		"agent.plugin_disabled":    "Plugin '%s' was disabled and stopped",
		"agent.plugin_skip":        "Plugin '%s' is disabled; skipped",
		"agent.plugin_config":      "Updated configuration for plugin '%s'",
		"agent.plugin_registered":  "Registered plugin '%s'",
		"agent.plugin_removed":     "Plugin '%s' was removed from modules.json and stopped",
		"agent.plugin_sig_ok":      "Verified plugin signature: %s",
		"agent.modules_changed":    "Change detected in modules.json; reloading",
		"agent.ws_connected":       "WebSocket connection established",
		"agent.sec_event_sent":     "Security event sent: [%s] %s (%s)",
		"agent.sec_event_failed":   "Failed to send security event: %v",
		"agent.sec_event_panic":    "Panic while draining security events: %v",
		"agent.manual_recv":        "Manual run request received: plugin=%s request_id=%s",
		"agent.manual_sent":        "Manual run result sent: plugin=%s status=%s duration=%dms",
		"agent.dep_missing":        "Required command not found: %s (used by %s)",
		"agent.dep_missing_list":   "Missing tools: %v — %s",

		// --- dashboard ---
		"dash.security_alert":      "Security alert: [%s] %s",
		"dash.start":               "Dashboard started (listen: %s)",
		"dash.static_dir":          "Static file directory: %s",
		"dash.shutdown_signal":     "Shutdown signal received",
		"dash.notify_on":           "Notifications: enabled",
		"dash.notify_off":          "Notifications: disabled (no channel configured)",
		"dash.alert_history":       "Alert history persisted to: %s",
		"dash.modules_loaded":      "Module configuration loaded: %s (%d modules)",
		"dash.agent_token_on":      "Agent token authentication: enabled",
		"dash.client_connected":    "Client connected: %s",
		"dash.agent_authenticated": "Agent authenticated: %s",
		"dash.agent_identified":    "Agent identified: %s",
		"dash.api_plugins":         "Plugin API enabled",
		"dash.api_metrics":         "Metrics API enabled",
		"dash.api_logs":            "Logs API enabled",
		"dash.api_config":          "Config API enabled",
		"dash.api_alert_history":   "Alert history API enabled",
		"dash.api_actions":         "One-click action API enabled",
		"dash.api_version":         "Version API enabled",
		"dash.api_metrics_hist":    "Metrics history API enabled",
		"dash.api_alert_settings":  "Alert settings API enabled",
		"dash.session_persist":     "Session persistence: %s (IP binding: %v)",
		"dash.session_no_persist":  "Session persistence: disabled (logout on restart)",
		"dash.public_viewer":       "Public viewer mode: enabled (CPU/memory/disk usage visible without login)",
		"dash.auth_on":             "Authentication: enabled (users: %d, users_file: %s)",
		"dash.auth_off":            "Authentication: disabled (set auth.enabled to true in dashboard_config.json to enable)",
		"dash.shutdown_stopping":   "Shutdown signal received; stopping server...",
		"dash.server_start":        "Server started: http://%s",
		"dash.server_stop":         "Server stopped",

		// --- batch 1: agent WARN/ERROR/startup INFO ---
		"agent.autoupdate_on":          "Auto-update is enabled. If the GitHub repository is compromised it leads to arbitrary code execution (%s)",
		"agent.sys_module_cfg_failed":  "Failed to configure system module: %v",
		"agent.sys_module_reg_failed":  "Failed to register system module: %v",
		"agent.sig_verify_disabled":    "Plugin signature verification: disabled — unsigned .so files are also loaded (enable with plugins.require_signature=true)",
		"agent.plugin_load_error":      "Plugin load error: %v",
		"agent.run_error":              "Agent run error: %v; reconnecting in 5 seconds",
		"agent.plugin_stop_failed":     "Failed to stop plugin '%s': %v",
		"agent.plugin_reconfig_failed": "Failed to reconfigure plugin '%s': %v",
		"agent.plugin_path_invalid":    "Invalid plugin_path for plugin '%s'",
		"agent.plugin_rejected":        "Rejected plugin '%s': %v",
		"agent.plugin_load_failed":     "Failed to load plugin '%s': %v",
		"agent.plugin_name_mismatch":   "Plugin '%s' registered itself as '%s' (does not match modules.json name); tracking it as '%s' to avoid missing events/backup",
		"agent.plugin_ctor_panic":      "Plugin constructor panicked: %v",
		"agent.plugin_reload_failed":   "Plugin reload failed: %v",
		"agent.ping_failed":            "Ping send failed: %v",
		"agent.read_error":             "Read error: %v",
		"agent.send_failed":            "Send failed: %v",
		"agent.status_sent":            "Status sent successfully",
		"agent.cmd_parse_failed":       "Command parse failed: %v",
		"agent.cmd_unknown":            "Unsupported action: %s",
		"agent.backup_panic":           "Panic during backup execution: %v",
		"agent.backup_json_failed":     "Failed to marshal backup_result: %v",
		"agent.backup_send_failed":     "Failed to send backup_result: %v",

		// --- batch 1: dashboard WARN/ERROR/startup INFO ---
		"dash.modules_load_error":       "Failed to load module configuration: %v",
		"dash.flood_detected":           "Connection flood detected: %d rejected (%s)",
		"dash.auth_reject_detected":     "Suspicious agent connections detected: %s x%d",
		"dash.agent_token_mismatch":     "Rejected connection with mismatched agent token: %s",
		"dash.ws_upgrade_failed":        "WebSocket upgrade failed: %v",
		"dash.agent_dup_rejected":       "Rejected a second agent connection (already connected): %s",
		"dash.read_error":               "Read error: %v",
		"dash.event_ignored":            "Ignored event from non-agent: %s",
		"dash.event_received":           "Event received: %s",
		"dash.cmd_ignored":              "Command received (ignored): %s",
		"dash.status_ignored":           "Ignored status from non-agent: %s",
		"dash.heuristic_rejected":       "Rejected heuristic promotion (already connected as agent): %s",
		"dash.pluginmgr_init_failed":    "PluginManager initialization failed: %v",
		"dash.plugin_api_disabled":      "Plugin API will be disabled",
		"dash.users_load_failed":        "Failed to load user store: %v",
		"dash.session_load_failed":      "Failed to load session persistence (continuing in-memory only): %v",
		"dash.users_corrupt":            "Authentication is enabled but users.json is corrupt; login is impossible until an administrator fixes it manually: %s",
		"dash.no_users":                 "Authentication is enabled but no user exists yet. Open /setup.html in a browser to create the administrator",
		"dash.agent_token_missing":      "Authentication is enabled but auth.agent_token is unset; the Agent cannot connect (set it to the same value as agent_config.json's token).",
		"dash.insecure_upload":          "Security warning: plugins_upload_enabled=true and auth.enabled=false. Anyone can install and run a plugin (.so) (effectively RCE). Either set auth.enabled=true or plugins_upload_enabled=false.",
		"dash.shutdown_error":           "Server shutdown error: %v",
		"dash.server_start_failed":      "Failed to start server: %v",
		"dash.alert_history_signed":     "Alert history HMAC signing: enabled (key: %s)",
		"dash.alert_history_key_failed": "Failed to load the alert-history signing key (continuing unsigned): %v",

		// --- batch 2: dashboard Hub / updater / alert / notify ---
		"dash.broadcast_error":          "Broadcast send error: %v; removing client",
		"dash.viewer_cap":               "Rejected connection: unauthenticated viewer cap (%d) reached",
		"dash.evict_viewer":             "Disconnected one unauthenticated viewer for an authenticated client (cap %d)",
		"dash.max_clients":              "Rejected connection: max clients (%d) reached",
		"dash.client_added":             "Client added: %s (%d connections)",
		"dash.client_removed":           "Client removed: %s (%d connections left)",
		"dash.client_close_error":       "Client close error: %v",
		"dash.invalid_status":           "Discarded invalid status: %v",
		"dash.broadcast_browsers_error": "BroadcastToBrowsers send error: %v",
		"updater.incomplete":            "Auto-update: incomplete configuration (repository_url / update_script)",
		"updater.enabled":               "Auto-update: enabled (check interval: %s, current: %s)",
		"updater.check_failed":          "Auto-update: version check failed: %v",
		"updater.latest":                "Auto-update: already up to date (%s)",
		"updater.new_version":           "Auto-update: new version detected %s -> %s; running update script",
		"updater.script_failed":         "Auto-update: script execution failed: %v",
		"updater.script_done":           "Auto-update: update script finished (applied on next start)",
		"updater.output":                "Auto-update: %s output:\n%s",
		"alert.history_load_failed":     "Failed to load alert history: %v",
		"notify.disabled":               "Notifications are disabled",
		"notify.discord_reg":            "Notification channel registered: discord (retries=%d, backoff max=%ds)",
		"notify.telegram_reg":           "Notification channel registered: telegram",
		"notify.line_reg":               "Notification channel registered: line",
		"notify.slack_reg":              "Notification channel registered: slack",
		"notify.email_reg":              "Notification channel registered: email",
		"notify.channel_count":          "Notification channel count: %d",
		"notify.batch_enabled":          "Notification batching: enabled (window=%s, exclude critical=%v)",
		"notify.send":                   "Notification sent: [%s] %s",
		"notify.concurrent_skip":        "Skipped send to [%s]: concurrency limit (%d) reached",
		"notify.timeout_skip":           "Skipped send to [%s]: critical notification wait timed out",
		"notify.panic":                  "Panic while sending notification [%s]: %v",
		"notify.failed":                 "Notification failed [%s]: %v",
		"notify.success":                "Notification succeeded [%s]",

		// --- batch 3a: internal/api / internal/auth ---
		"api.bwrap_missing":           "bwrap required to isolate plugin inspection was not found (%s); uploads will be rejected (set plugins.inspect_isolation=\"off\" for the old behavior): %v",
		"api.plugin_run_request":      "Sent manual run request: plugin=%s request_id=%s",
		"api.plugin_upload_recv":      "Plugin upload received: %s (%d bytes) from %s",
		"api.plugin_sig_failed":       "Rejected plugin: signature verification failed: %s: %v",
		"api.plugin_sig_ok":           "Verified plugin signature (before inspection): %s",
		"api.plugin_verify_failed":    "Rejected plugin: inspection failed: %s: %v",
		"api.module_register_failed":  "Module registration failed: %s: %v",
		"api.plugin_so_delete_failed": "Failed to delete plugin .so: %s: %v",
		"api.plugin_module_deleted":   "Plugin module deleted: %s",
		"api.alertcfg_updated":        "Updated alert thresholds and saved to dashboard_config.json",
		"auth.setup_done":             "Initial setup complete: created administrator '%s'",
		"auth.login_locked":           "Login attempt while locked out: ip=%s",
		"auth.login_failed":           "Login failed: user=%s from=%s",
		"auth.login_success":          "Login succeeded: user=%s role=%s from=%s",
		"auth.guest_login":            "Guest login: role=viewer from=%s",
		"auth.password_changed":       "Password changed: user=%s",
		"auth.user_created":           "User created: %s (role=%s)",
		"auth.user_deleted":           "User deleted: %s",
		"auth.avatar_updated":         "Avatar updated: user=%s",
	},
}
